<?php

namespace Database\Factories;

use App\Models\Complaint;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ComplaintSubject>
 *
 * Note: incident_summary lives on the complaint itself now (one shared
 * narrative per complaint, not one per subject) — see ComplaintFactory.
 * The complaint's one PDF form is generated by ComplaintSeeder once all of
 * a complaint's subjects exist, not per-subject here.
 */
class ComplaintSubjectFactory extends Factory
{
    public function definition(): array
    {
        return [
            'complaint_id' => Complaint::factory(),
            'student_id' => User::factory(),
        ];
    }
}
