<?php

namespace Database\Factories;

use App\Models\Complaint;
use App\Models\User;
use App\Models\Violation;
use Database\Factories\Concerns\GeneratesSampleFiles;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\File;
use Carbon\Carbon;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Complaint>
 */
class ComplaintFactory extends Factory
{
    use GeneratesSampleFiles;

    /**
     * Define the model's default state.
     *
     * Note: this only fills the complaint table's own columns. The subject(s)
     * of the complaint live in the separate complaint_subject table and are
     * not something a single-model factory can set — wire those up after
     * creating the complaint (see database/seeders/ComplaintSeeder.php).
     * Their per-subject PDF is generated by ComplaintSubjectFactory instead,
     * once the subject (and therefore the student) is known.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $violation = Violation::inRandomOrder()->first();
        $complainant = User::inRandomOrder()->first();

        $createdAt = $this->faker->dateTimeBetween('-1 year', 'now');
        $confirmedAt = Carbon::parse($createdAt)->addDays(rand(1, 5));
        $status = $this->faker->randomElement(['pending', 'ongoing', 'ongoing', 'resolved', 'resolved', 'rejected']);

        // Matches the real "{MMDDYY}{daily-seq}" format from
        // GeneratesSequenceCode/ComplaintController::generateComplaintNumber().
        $prefix = Carbon::parse($createdAt)->format('mdy');
        $sequence = Complaint::where('complaint_number', 'like', "{$prefix}%")->count() + 1;

        return [
            'complaint_number' => $prefix . str_pad($sequence, 2, '0', STR_PAD_LEFT),
            'case_number' => $status !== 'pending' ? $this->faker->unique()->numberBetween(1000, 9999) : null,
            'complainant_id' => $complainant?->id,
            'incident_id' => $violation?->id,
            'complaint_description' => $this->faker->paragraph(2),
            'complaint_evidences' => null, // filled in by configure() below, once the folder/files exist
            'rejected_reason' => $status === 'rejected' ? $this->faker->sentence(8) : null,
            'rejected_at' => $status === 'rejected' ? $confirmedAt : null,
            'confirmed_at' => $status !== 'pending' ? $confirmedAt : null,
            'complaint_status' => $status,
            'resolved_at' => $status === 'resolved' ? Carbon::parse($confirmedAt)->addDays(rand(1, 10)) : null,
            'archived_at' => in_array($status, ['resolved', 'rejected']) ? Carbon::parse($confirmedAt)->addYears(5) : null,
            'created_at' => $createdAt,
        ];
    }

    public function configure(): static
    {
        return $this->afterCreating(function (Complaint $complaint) {
            $folder = storage_path("app/private/complaints/complaint-{$complaint->complaint_number}");
            File::ensureDirectoryExists("{$folder}/subjects");
            File::ensureDirectoryExists("{$folder}/evidences");

            $count = random_int(1, 3);
            $evidences = [];
            for ($i = 1; $i <= $count; $i++) {
                $fileName = "{$i}-{$complaint->complaint_number}.jpg";
                $this->makePlaceholderImage("{$folder}/evidences/{$fileName}", 'Complaint Evidence');
                $evidences[] = ['type' => 'pic', 'file' => $fileName];
            }

            $complaint->update(['complaint_evidences' => json_encode($evidences)]);
        });
    }
}
