<?php

namespace Database\Factories;

use App\Models\Referral;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\File;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Referral>
 *
 * Note: this only fills the referral table's own columns. The referred
 * student(s) live in the separate referral_referred_student table and are
 * not something a single-model factory can set — wire those up after
 * creating the referral (see database/seeders/ReferralSeeder.php). Their
 * per-student PDF is generated by ReferralReferredStudentFactory instead,
 * once the student is known.
 */
class ReferralFactory extends Factory
{
    public function definition(): array
    {
        $programHead = User::where('role', 'sub_admin')->inRandomOrder()->first()
            ?? User::inRandomOrder()->first();

        $createdAt = $this->faker->dateTimeBetween('-1 year', 'now');
        $confirmedAt = Carbon::parse($createdAt)->addDays(rand(1, 5));
        $status = $this->faker->randomElement(['pending', 'approved', 'approved', 'rejected']);

        // Matches the real "{MMDDYY}{daily-seq}" format from
        // GeneratesSequenceCode/ReferralController.
        $prefix = Carbon::parse($createdAt)->format('mdy');
        $sequence = Referral::where('referral_number', 'like', "{$prefix}%")->count() + 1;

        return [
            'program_head_id' => $programHead?->id,
            'referral_number' => $prefix . str_pad($sequence, 2, '0', STR_PAD_LEFT),
            'reason_description' => $this->faker->paragraph(2),
            'referral_status' => $status,
            'rejected_reason' => $status === 'rejected' ? $this->faker->sentence(8) : null,
            'rejected_at' => $status === 'rejected' ? $confirmedAt : null,
            'send_to_guidance' => $this->faker->boolean(40) ? 1 : 0,
            'confirmed_at' => $status === 'approved' ? $confirmedAt : null,
            'archived_at' => $status !== 'pending' ? Carbon::parse($confirmedAt)->addYears(5) : null,
            'created_at' => $createdAt,
        ];
    }

    public function configure(): static
    {
        return $this->afterCreating(function (Referral $referral) {
            File::ensureDirectoryExists(storage_path("app/private/referrals/referral-{$referral->referral_number}"));
        });
    }
}
